"""initial schema

Revision ID: 946abecd3e6c
Revises: 
Create Date: 2026-08-15 22:34:54.450231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946abecd3e6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ADVISOR', 'STUDENT', name='role', native_enum=False), nullable=False),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('advisor_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisor_id', 'student_id', name='uq_advisor_student')
    )
    op.create_index(op.f('ix_advisor_students_advisor_id'), 'advisor_students', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_advisor_students_student_id'), 'advisor_students', ['student_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_index(op.f('ix_audit_logs_plan_id'), 'audit_logs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_student_id'), 'audit_logs', ['student_id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'GENERATED', 'SENT', 'ARCHIVED', name='planstatusdb', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_version', sa.String(length=64), nullable=True),
    sa.Column('renderer_version', sa.String(length=64), nullable=True),
    sa.Column('plan_hash', sa.String(length=40), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('image_file_id', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_advisor_status', 'weekly_plans', ['advisor_id', 'status'], unique=False)
    op.create_index('ix_plan_student_week', 'weekly_plans', ['student_id', 'week_start'], unique=False)
    op.create_index(op.f('ix_weekly_plans_plan_hash'), 'weekly_plans', ['plan_hash'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_plan_id'), 'assignments', ['plan_id'], unique=False)
    op.create_table('plan_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=12), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'weekday', name='uq_plan_weekday')
    )
    op.create_index(op.f('ix_plan_days_plan_id'), 'plan_days', ['plan_id'], unique=False)
    op.create_table('plan_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_hash', sa.String(length=40), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('template_version', sa.String(length=64), nullable=False),
    sa.Column('renderer_version', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_files_plan_id'), 'plan_files', ['plan_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_day_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_day_id', 'slot_index', name='uq_day_slot')
    )
    op.create_index(op.f('ix_activities_plan_day_id'), 'activities', ['plan_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_plan_day_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_plan_files_plan_id'), table_name='plan_files')
    op.drop_table('plan_files')
    op.drop_index(op.f('ix_plan_days_plan_id'), table_name='plan_days')
    op.drop_table('plan_days')
    op.drop_index(op.f('ix_assignments_plan_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_weekly_plans_plan_hash'), table_name='weekly_plans')
    op.drop_index('ix_plan_student_week', table_name='weekly_plans')
    op.drop_index('ix_plan_advisor_status', table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_audit_logs_student_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_plan_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_advisor_students_student_id'), table_name='advisor_students')
    op.drop_index(op.f('ix_advisor_students_advisor_id'), table_name='advisor_students')
    op.drop_table('advisor_students')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
